---
- name: Nginx Server
  hosts: web1

  tasks:
  - name: Install Nginx Server
    yum:
      name: nginx
      state: present
 
  - name: Ensure that service will start after a reboot
    service:
      name: nginx
      enabled: yes

  - name: Start Nginx Server
    service:
      name: nginx
      state: started