---
- hosts: all
  tasks:
    - name: Install and configure httpd web server
      when: ansible_distribution == "CentOS"
      block:
        - yum:
            name: httpd
            state: present
            
        - service:
            name: httpd
            state: started
            enabled: yes  