---
- name: Install httpd
  hosts: web1
  gather_facts: no
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Do not remove this task
      command: /bin/false
      ignore_errors: yes
      register: results

    - shell: "echo {{ results.msg }} > /tmp/output"
    
    - name: start service
      service:
        name: httpd
        state: started