---
- name: Deploy lamp stack application
  hosts: all
  become: yes
  roles:
    - common

- name: Deploy lamp stack application
  hosts: lamp-db
  gather_facts: yes
  become: yes
  roles:
    - mysql

- name: Deploy lamp stack application
  hosts: web_servers
  gather_facts: yes
  become: yes
  roles:
    - httpd-php