---
# Write a playbook to copy the secret file located at /home/thor/playbooks/secrets_file.txt to all remote hosts at location /root/.secrets_file.txt

# Your playbook must be located at: /home/thor/playbooks/copy_secrets.yml
# Remote hosts are placed in inventory: /home/thor/playbooks/inventory
# The secret file is encrypted, please use vault password from /home/thor/playbooks/vault_pass.txt while you execute the playbook

- hosts: all
  tasks:
    - name: copy a secret file to remote hosts
      copy:
        src: secrets_file.txt
        dest: /root/.secrets_file.txt